/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.97
 * Generated at: 2024-12-05 02:48:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.sample;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Date;

public final class hello2_jsp extends HttpJspBase implements JspSourceDependent, JspSourceImports {

	//멤버변수선언영역
	String declation = "멤버변수선언문입니다.";
	//멤버함수영역
	public String getDeclation() {
		return declation;
	}
	//멤버함수영역(오버라이딩)
	// init()
	public void _jspInit() {
	}

	// destroy()
	public void _jspDestroy() {
	}

	// service(request, response)
	public void _jspService(final javax.servlet.http.HttpServletRequest request,
			final javax.servlet.http.HttpServletResponse response)
			throws java.io.IOException, javax.servlet.ServletException {

		final javax.servlet.jsp.PageContext pageContext;
		javax.servlet.http.HttpSession session = null;
		final javax.servlet.ServletContext application;
		final javax.servlet.ServletConfig config;
		javax.servlet.jsp.JspWriter out = null;
		final java.lang.Object page = this;
		javax.servlet.jsp.JspWriter _jspx_out = null;
		javax.servlet.jsp.PageContext _jspx_page_context = null;

		try {
			response.setContentType("text/html; charset=UTF-8");
			application = pageContext.getServletContext();
			config = pageContext.getServletConfig();
			session = pageContext.getSession();
			out = pageContext.getOut();

			out.write("\r\n");
			out.write("\r\n");
			out.write("<!DOCTYPE html>\r\n");
			out.write("<html>\r\n");
			out.write("<head>\r\n");
			out.write("<meta charset=\"UTF-8\">\r\n");
			out.write("<title>Insert title here</title>\r\n");
			out.write("</head>\r\n");
			out.write("<body>\r\n");
			out.write("	<h1>현재 날짜 시간은 = ");
			out.print((new Date()).toString());
			out.write("</h1>\r\n");
			out.write("\r\n");
			out.write("</body>\r\n");
			out.write("</html>");
		} catch (java.lang.Throwable t) {
			
		} finally {
			_jspxFactory.releasePageContext(_jspx_page_context);
		}
	}
}
